default_stages: [pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.0.0
    hooks:
      - id: eslint
        args: ["--fix"]
      - id: eslint-no-regex
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.15.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args: [--quiet, --config, pyproject.toml]
