name: unittests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-packages:
    name: Run unit tests and upload coverage
    runs-on: ${{ matrix.os }}
    env:
      USING_COVERAGE: '3.10'
    strategy:
      matrix:
        os: [ubuntu-latest , macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install project dependencies
        run: poetry install --no-interaction --no-root

      - name: Lint code with ruff
        run: poetry run ruff check skdataset

      - name: Format code with black
        run: poetry run black skdataset

      - name: Run unit tests
        run: poetry run pytest skdataset/tests

      - name: Generate coverage report
        run: poetry run coverage run --source=skdataset -m pytest skdataset/tests && poetry run coverage xml
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: hadi-gharibi/scikit-dataset
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
